### ISSUE TITLE
Remove blueprint for direct dependencies.

### ISSUE THREAD

**Issue by rwjblue** [BrianSipple/ember-stagger-swagger#1]
[These lines](https://github.com/BrianSipple/ember-stagger-swagger/blob/master/blueprints/ember-stagger-swagger/index.js#L25-L31) are adding packages to the consuming project, but should really just be added to this projects list of dependencies. Adding them to the consuming project happens to work (due to node module resolution traversing upwards), but it is generally not great to add packages to the project if the project itself doesn't need to consume them.  In this case, these packages are only used from within ember-stagger-swagger's `index.js` so putting them in [dependencies here](https://github.com/BrianSipple/ember-stagger-swagger/blob/master/package.json#L55) is the right way to go...

**Comment by BrianSipple** [comment]
Thanks for clarifying this! I've been going between both approaches after encountering a similarly-themed question in [ember-cli-eslint](https://github.com/jonathanKingston/ember-cli-eslint/pull/43), but now it clicked -- the distinction between whether or not the project itself needs to consume them.

**Comment by BrianSipple** [comment]
Addressed in https://github.com/BrianSipple/ember-stagger-swagger/releases/tag/v1.0.4
